# Site settings
title: James Senior Park
url: "https://karla11.github.io"
baseurl: ""
description: >
    제임스 블로그

# My information
email: daeupak@gmail.com
author: James Senior Park
profile: 유물론자
twitter_username: 
github_username: karla11
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: karla11
  shortname: karla11
utterances:
  repo: karla11/karla11.github.io
  issue-term: url
  label: Comment
  branch: master

google_analytics:
  ua:

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/karla11/karla11.github.io/blame/master/_wiki"
edit: "https://github.com/karla11/karla11.github.io/edit/master/_wiki"
issue: "https://github.com/karla11/karla11.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
